name: solscore-fastapi

services:
  api:
    build: .
    container_name: solscore_fastapi
    ports:
      - "127.0.0.1:8082:8000"
    volumes:
      - ./app:/srv/app
      - ./.env:/srv/.env:ro
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-include", ".env"]
